kind: pipeline
type: docker
name: default
steps:
- name: awscli-test
  image: ramalingam81/awscli-env:ENV
  commands: 
  - cat /root/.aws/credentials
  - aws s3 ls
  settings:
    AWS_ACCESS_KEY_ID: 
      from_secret: AWS_ACCESS_KEY_ID
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_REGION: ap-south-1
