pipeline:
  test:
    image: quay.io/honestbee/awscli:1.11.55
    environment:
      - AWS_DEFAULT_REGION=ap-south-1
      - AWS_DEFAULT_OUTPUT=json
    commands:
      - aws s3 ls
      - aws ec2 describe-vpcs | jq --raw-output '.Vpcs[] | select(.IsDefault==true) | .CidrBlock ' 
