kind: pipeline
type: docker
name: default
steps:
- name: awscli-test
  image: ramalingam81/awscli-env:ENV
  commands: 
  - cat /root/.aws/credentials
  - aws s3 ls
  settings:
    access_key: 
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    region: ap-south-1
